<?php
  function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
      'title' => 'cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    return $items;
  }

  function cipher_form() {
    $form['shift_value'] = array(
      '#title' => 'Shift Value',
      '#description' => 'Please input number (positive integer)',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => true,
    );

    $form['direction'] = array(
      '#title' => 'Shift Direction',
      '#description' => 'Type either right or left',
      '#type' => 'textfield',
      '#element_validate' => array('direction_validate'),
      '#required' => true,
    );

    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#description' => 'Plase input any phrases',
      '#type' => 'textfield',
      '#element_validate' => array('phrase_validate'),
      '#required' => true,
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );


    return $form;
  }


  //ELEMENT VALIDATION HELPER
    function direction_validate($element) {
      $received_input = trim($element['#value']);
      if ($received_input != 'right' && $received_input != 'left') {
       form_error($element, t('please type either "right" or "left"'));
      }
    }

    function phrase_validate($element) {
      $split_str = str_split($element['#value']);
      for($i=0; $i<count($split_str); $i++){
        if(!ctype_punct($split_str[$i]) && !ctype_alpha($split_str[$i]) && !ctype_space($split_str[$i])){
          form_error($element, t('only alphabet, spaces, and punctuation are allowed'));
        }
      }
    }


    // $s_alphabet = range("a", "z");
    // $l_alphabet = range("A", "Z");

    // $s_alphabet = array["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];
    //
    // $l_alphabet = array["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"];
