<?php
  function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
      'title' => 'cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );

    $items['cipher_result'] = array(
      'title' => 'result',
      'page callback' => 'show_cipher_result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  //////////////////////////
  //FORM
  function cipher_form() {
    $form['shift_value'] = array(
      '#title' => 'Shift Value',
      '#description' => 'Please input number (positive integer)',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => true,
    );

    $form['direction'] = array(
      '#title' => 'Shift Direction',
      '#description' => 'Type either right or left',
      '#type' => 'textfield',
      '#element_validate' => array('direction_validate'),
      '#required' => true,
    );

    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#description' => 'Plase input any phrases',
      '#type' => 'textfield',
      '#element_validate' => array('phrase_validate'),
      '#required' => true,
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );
    return $form;
  }
  //END OF FORM
  //////////////////////////



  //////////////////////////
  //ELEMENT VALIDATION HELPER
    function direction_validate($element) {
      $received_input = trim($element['#value']);
      if ($received_input != 'right' && $received_input != 'left') {
       form_error($element, t('please type either "right" or "left"'));
      }
    }

    function phrase_validate($element) {
      $split_str = str_split($element['#value']);
      for($i=0; $i<count($split_str); $i++){
        if(!ctype_punct($split_str[$i]) && !ctype_alpha($split_str[$i]) && !ctype_space($split_str[$i])){
          form_error($element, t('only alphabet, spaces, and punctuation are allowed'));
        }
      }
    }
  //END OF ELEMENT VALIDATION HELPER
  //////////////////////////




  //////////////////////////
  //SHIFT CIPHER LOGIC
  function cipher_form_submit($form, &$form_state){

    //Get user input from form
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];

    //create alphabet list (array(a~z))
    $alphabet_list = range("a", "z");

    //create split user input as array
    $split_str = str_split(strtolower($form_state['values']['phrase']));

    //eliminate overlooping
    if($shift_value > 26){
      $cycle = floor($shift_value / 26);
      $shift_value -= 26 * $cycle;
    }

    //change direction based on user's direction input
    if($direction == 'left'){
      $shift_value = -1 * $shift_value;
    }

    for($i=0; $i<count($split_str); $i++){

      //if the character was alphabet, replace the character
      if(ctype_alpha($split_str[$i])){
        //check corresponding key number
        $key = array_search($split_str[$i], $alphabet_list, true);
        $replace_key = $key + $shift_value;

          //if the number reached over 25 or less than 0, make loop
          if($replace_key > 25) {
            $replace_key -= 26;
          }

          if($replace_key < 0) {
            $replace_key += 26;
          }
          $split_str[$i] = $alphabet_list[$replace_key];
      }
    }

    //save to SESSION and navigate to cipher_result
    $_SESSION['output'] = implode($split_str);
    $form_state['redirect'] = 'cipher_result';
  }
  //SHIFT CIPHER LOGIC END//
  //////////////////////////



  //////////////////////////
  //DISPLAY RESULT
  function show_cipher_result() {
    return "".$_SESSION['output'];
  }
  //DISPLAY RESULT END
  //////////////////////////
