<?php
  function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
      'title' => 'cipher',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('cipher_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );

    $items['cipher_result'] = array(
      'title' => 'result',
      'page callback' => 'show_cipher_result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );


    return $items;
  }

  function cipher_form() {
    $form['shift_value'] = array(
      '#title' => 'Shift Value',
      '#description' => 'Please input number (positive integer)',
      '#type' => 'textfield',
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => true,
    );

    $form['direction'] = array(
      '#title' => 'Shift Direction',
      '#description' => 'Type either right or left',
      '#type' => 'textfield',
      '#element_validate' => array('direction_validate'),
      '#required' => true,
    );

    $form['phrase'] = array(
      '#title' => 'Phrase',
      '#description' => 'Plase input any phrases',
      '#type' => 'textfield',
      '#element_validate' => array('phrase_validate'),
      '#required' => true,
    );

    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'submit',
    );
    return $form;
  }


  //ELEMENT VALIDATION HELPER
    function direction_validate($element) {
      $received_input = trim($element['#value']);
      if ($received_input != 'right' && $received_input != 'left') {
       form_error($element, t('please type either "right" or "left"'));
      }
    }

    function phrase_validate($element) {
      $split_str = str_split($element['#value']);
      for($i=0; $i<count($split_str); $i++){
        if(!ctype_punct($split_str[$i]) && !ctype_alpha($split_str[$i]) && !ctype_space($split_str[$i])){
          form_error($element, t('only alphabet, spaces, and punctuation are allowed'));
        }
      }
    }
  //END OF ELEMENT VALIDATION HELPER





  //
  function cipher_form_submit($form, &$form_state){

    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $alphabet_list = range("a", "z");
    $split_str = str_split(strtolower($form_state['values']['phrase']));


    if($direction == 'left'){
      $shift_value = -1 * $shift_value;
    }

    for($i=0; $i<count($split_str); $i++){
      if(ctype_alpha($split_str[$i])){
        $key = array_search($split_str[$i], $alphabet_list, true);
        $replace_key = $key + $shift_value;

        if(isset($replace_key)){
          if($replace_key > 25) {
            $replace_key -= 26;
          }

          if($replace_key < 0) {
            $replace_key += 26;
          }

          $split_str[$i] = $alphabet_list[$replace_key];
        }
      }
    }

    $_SESSION['output'] = implode($split_str);
    $form_state['redirect'] = 'cipher_result';
  }

  function show_cipher_result() {
    return "".$_SESSION['output'];
  }
